// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("ReactiveUI.Autofac")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2016 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0+1.Branch.master.Sha.f51775c9fd4fd276af2045e4f6074e5d5ea4066d")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
        internal const string InformationalVersion = "0.1.0+1.Branch.master.Sha.f51775c9fd4fd276af2045e4f6074e5d5ea4066d";
    }
}
