// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("ReactiveUI.Autofac")]
[assembly: AssemblyCompanyAttribute("Alexey Zimarev")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2016 Alexey Zimarev")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-unstable.2+Branch.develop.Sha.977cc85af2f77511804dd520380baf7d66cc2375")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
        internal const string InformationalVersion = "0.1.0-unstable.2+Branch.develop.Sha.977cc85af2f77511804dd520380baf7d66cc2375";
    }
}
